"""initial_schema

Revision ID: 61fd04709d72
Revises: 
Create Date: 2026-07-23 15:57:30.680848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61fd04709d72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('thinking', sa.JSON(), nullable=True))
    op.add_column('chat_sessions', sa.Column('context', sa.JSON(), nullable=True))
    op.alter_column('knowledge_documents', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('knowledge_documents', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('logs', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('logs', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('logs', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('knowledge_documents', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('knowledge_documents', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('chat_sessions', 'context')
    op.drop_column('chat_messages', 'thinking')
    # ### end Alembic commands ###
