"""create initial tables

Revision ID: de3fe238cf0f
Revises: 6ecbd9e1ec74
Create Date: 2026-07-17 16:56:28.172952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3fe238cf0f'
down_revision: Union[str, None] = '6ecbd9e1ec74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
